baseURL: "https://exam-box.dmi.unict.it"
theme: "up-business-theme"
languageCode: "en-us"

title: "ExamBox"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "ExamBox"
  description: "We specialize in providing services to desing websites, applications, build and maintain business for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "Department of Mathematics and Computer Science, University of Catania, Italy"

  contact:
    - "exambox@dmi.unict.it"

  copyright: "Developed by Davide Carnemolla & Mario Di Raimondo"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Blog"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Login"
      url: "https://admin.exam-box.dmi.unict.it"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "How it works"
      url: "/#"
      weight: 2

    - name: "Our team"
      url: "/#"
      weight: 3

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
